pageinfo = [[1234625145,9359],
	[1262976653,1813],
	[1262976041,13458],
	[1262976083,13375],
	[1262974947,18493],
	[1233679773,1666],
	[1233664825,1708],
	[1262975989,11870],
	[1262976053,11762],
	[1262975241,9379],
	[1262976113,20155],
	[1233338263,2811],
	[1262976775,8518],
	[1233679247,1657],
	[1234625027,1215],
	[1262975287,7399],
	[1234625129,3175],
	[1262977484,3396],
	[1262977421,3369],
	[1233679383,2171],
	[1262977351,4326],
	[1262977385,9026],
	[1262977357,2229],
	[1262977375,2145],
	[1262977411,2663],
	[1262977415,3147],
	[1262977445,2573],
	[1262975241,2585],
	[1262977363,3270],
	[1262977425,3499],
	[1262977343,3108],
	[1262977407,3226],
	[1262977429,3143],
	[1262977401,4593],
	[1262977449,3718],
	[1262977397,6936],
	[1262977453,3432],
	[1262977435,3156],
	[1262977439,3145],
	[1262977461,2631],
	[1262977457,3259],
	[1233601361,2057],
	[1234625135,1261],
	[1233930135,1767],
	[1234625007,2212],
	[1234624769,3504],
	[1234624883,4479],
	[1234625011,5802],
	[1234624971,4365],
	[1234624865,3919],
	[1234624877,3683],
	[1234625015,4748],
	[1234624995,2057],
	[1234624909,3338],
	[1234624925,3418],
	[1234624931,2778],
	[1234624935,2761],
	[1234624999,4407],
	[1234624945,3657],
	[1234625003,3435],
	[1262976685,12169],
	[1262975463,8033],
	[1234625105,3586],
	[1233764933,1697],
	[1262975953,32846],
	[1233764925,1665],
	[1233764941,1696],
	[1233764937,1694],
	[1234629101,2544],
	[1262976573,4605],
	[1262975241,8286],
	[1233764923,1681],
	[1262977335,2736],
	[1233764931,1711],
	[1262977307,5059],
	[1262975241,16159],
	[1262975667,12589],
	[1262975241,8579],
	[1262976649,1821],
	[1233764513,2038],
	[1234629093,4077],
	[1262975969,18881],
	[1234625499,8290],
	[1262976627,10217],
	[1262975933,7256],
	[1262975723,7391],
	[1262975743,3885],
	[1262975825,16112],
	[1262975241,10622],
	[1262976495,6871],
	[1234625033,1222],
	[1234625047,1220],
	[1262977319,5722],
	[1262975639,27690],
	[1233934889,3872],
	[1262976457,3041]];
pagedata = [ ["./documents.html","Documents","﻿This category contains the tools required to create and print all primary documents such as invoices, goods receipt and goods dispatch slips, pri...",""],
["./editing.html","Editing","﻿Editing warehouse or store description Top Previous Next error ",""],
["./editpaydocin.html","Editing","﻿Editing incoming payments Top Previous Next • Post - toggles posted/unposted status • No. - internal document ID number • Payment type - cash or ...",""],
["./editpaydocout.html","Editing","﻿Editing outgoing payments Top Previous Next • Post - toggles posted/unposted status • No. - internal document ID number • Payment type - cash or ...",""],
["./features.html","Features","﻿OK-Inventory is an innovative, versatile and customizable software package designed to provide inventory control, accounting and document managem...",""],
["./financial.html","Finances","﻿Finances Top Previous Next Error ",""],
["./fmpdcharge.html","Additional expenses","﻿Additional expenses Top Previous Next Error ",""],
["./fmpdin.html","Incoming","﻿Incoming payments Top Previous Next Filter panel At the top of the window there is a bar with a few sorting options available to you. You may sel...",""],
["./fmpdout.html","Outgoing","﻿Outgoing payments Top Previous Next Filter panel At the top of the window there is a bar with a few sorting options available to you. You may sel...",""],
["./fmwaybillmov.html","Goods transfer slips","﻿Goods transfer slips Top Previous Next Documents table • - indicates Goods transfer slip document type • - means the document is Posted. • No. - ...",""],
["./fmwmat.html","Warehouses management","﻿Warehouses management Top Previous Next Products list The following categories are available under Product section: Product Name, model, unit of ...",""],
["./frmstartwiz.html","Wizards","﻿Database Creation and Registering Wizards Top Previous Next There are two wizards available: • New database Wizard - Helps you create a blank dat...",""],
["./glossary.html","Glossary","﻿A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B Base currency - the main currency that you use everyday for your business activity. OK-In...",""],
["./internet.html","Internet","﻿Internet Top Previous Next Error ",""],
["./linked_documents.html","Linked_Documents","﻿Error ",""],
["./login.html","Login form","﻿This is the first form you&#39;ll see after the OK-Inventory startup. OK-Inventory is a multi-user system by design. This means that more than one us...",""],
["./new_database_wizard.html","New Database Wizard","﻿At welcome screen just click \"Next\" button to bring up the window for Name and Path settings: 1. Under \"Database name\" enter the name of a new da...",""],
["./ok_sklad_en_ftsearch.html","OK-Inventory","﻿OK-Inventory Contents &#166; Index &#166; Search Enter one or more keywords to search (&#39;*&#39; and &#39;?&#39; wildcards are supported): You must have JavaScript enabl...",""],
["./opttsao.html","Invoices","﻿Invoices Top Previous Next At the top of the window there is a field with default quantity of goods to be entered into goods receipt slips, sugge...",""],
["./opttsbackupdbs.html","Backups","﻿Backups Top Previous Next Error ",""],
["./opttsbarcodes.html","Bar codes","﻿Bar codes Top Previous Next Weight-bearing barcodes can be extremely useful when you sell a big piles of some products repacked into smaller ones...",""],
["./opttscommon.html","General","﻿General Top Previous Next • Language - change interface language here. It can be different for each user. • Printed forms language - Language use...",""],
["./opttscurrency.html","Currency","﻿Currency Top Previous Next If the exchange rate is not set for the date used in the document then the \"Edit exchange rate\" form will pop-up to se...",""],
["./opttsfinance.html","Finances","﻿Finances Top Previous Next Does not allows to create payment in advance types ",""],
["./opttsintf.html","Interface","﻿\"Interface\" settings Top Previous Next Select color to highlight evens - uses this color to differentiate odd lines from even in various tabled d...",""],
["./opttsinv.html","Inventory statements","﻿Inventory statements Top Previous Next Check \"Auto-numbering\" in case you wish to use auto numbering for your stock balances. For better traceabi...",""],
["./opttslogo.html","Logo","﻿\"Logo\" settings Top Previous Next Here you can set the logo of your enterprise to be printed on various forms and reports. Click on button to sel...",""],
["./opttsoperlog.html","Event Log","﻿\"Event Log\" settings Top Previous Next These options control what information will be store in the event or say operations log. In the event log ...",""],
["./opttsordersin.html","Customer orders","﻿Customer orders Top Previous Next At the top of the window there is a field with default product quantity to be written off, suggested by the sys...",""],
["./opttsordersout.html","Orders to supplier","﻿Orders to supplier Top Previous Next At the top of the window there is a field with default product quantity to be written off, suggested by the ...",""],
["./opttspdcharge.html","Additional charges","﻿\"Additional charges\" settings Top Previous Next Check \"create document as posted\" if you wish to automatically post the the documents after they ...",""],
["./opttspdin.html","Incoming payments","﻿\"Incoming payments\" settings Top Previous Next Check \"create document as posted\" if you wish to automatically post the the documents after they a...",""],
["./opttspdout.html","Outgoing payments","﻿\"Outgoing payments\" settings Top Previous Next Check \"create document as posted\" if you wish to automatically post the the documents after they a...",""],
["./opttswbin.html","Goods receipt slips","﻿\"Goods receipt slips\" settings Top Previous Next At the top of the window there is a field with default quantity of goods to be entered into good...",""],
["./opttswbmove.html","Stock transfer slips","﻿\"Stock transfer slips\" settings Top Previous Next At top of the window there is a field with default quantity, suggested by the system. You may c...",""],
["./opttswbout.html","Goods dispatch slips","﻿Goods dispatch slips Top Previous Next At the top of the window there is a field with default quantity of goods to be entered into goods receipt ...",""],
["./opttswbrest.html","Stock balance entry","﻿Stock balance entry Top Previous Next At the top of the window there is a field with default quantity, suggested by the system. You may change th...",""],
["./opttswbretin.html","Returns from customers","﻿Returns from customers Top Previous Next Check \"Auto-numbering\" in case you wish to use auto numbering for your stock balances. For better tracea...",""],
["./opttswbretout.html","Returns to supplier","﻿Returns to supplier Top Previous Next Check \"Auto-numbering\" in case you wish to use auto numbering for your stock balances. For better traceabil...",""],
["./opttswh.html","Warehouse","﻿Warehouse Top Previous Next Highlight products with quantity below - All the products that have their \"minimum amount that should be available at...",""],
["./optwriteoff.html","Write-off statements","﻿Write-off statements Top Previous Next At the top of the window there is a field with default product quantity to be written off, suggested by th...",""],
["./payments.html","Payments","﻿Payments Top Previous Next The OK-Inventory supports registering and processing of both incoming and outgoing payments You may register payments ...",""],
["./register_database_wizard.html","Register Database Wizard","﻿Error ",""],
["./rep1.html","Short income report","﻿Short income report Top Previous Next Error ",""],
["./rep10.html","Turnover report","﻿Turnover report Top Previous Next This report represents an expanded list indicating goods balances for the beginning of period, received and shi...",""],
["./rep11.html","Document log","﻿Document Log Top Previous Next This report contains the information on all operations performed by the company -- user of this program indicating...",""],
["./rep13.html","Sales report with profit","﻿Sales report with profit Top Previous Next This report contains the information on the value of all goods shipped to customers indicating profits...",""],
["./rep14.html","Sales rating","﻿Sales rating Top Previous Next This report allows the user to define sales rating per one of the three criteria: sales profits, relative profit o...",""],
["./rep15.html","Sales dynamics","﻿Sales dynamics Top Previous Next This report contains the information on sales dynamics for the period specified by user represented graphically....",""],
["./rep16.html","Expense reports","﻿Expense reports Top Previous Next This report contains the information on all expenses incurred by the company -- program user indicating the dat...",""],
["./rep17.html","Report on financial results","﻿Report on financial results Top Previous Next This report represents a combined form containing the information on all operations of goods sales ...",""],
["./rep18.html","Report on minimal goods balances","﻿Report on minimal goods balances Top Previous Next This report contains the information on goods at warehouse (all warehouse of the company -- us...",""],
["./rep2.html","Short sales report","﻿Short sales report Top Previous Next This report contains the information on goods sales volumes for any period of time selected by users both by...",""],
["./rep3.html","Sales reports on business partners","﻿Sales reports on business partners Top Previous Next This report contains the information on all sales documents issued to customers indicating d...",""],
["./rep4.html","Goods received report on suppliers","﻿Goods received report on suppliers Top Previous Next This report contains the information on all purchasing documents received from suppliers ind...",""],
["./rep5.html","Lenders list","﻿Lenders list Top Previous Next This report contains the information on all business partners - lenders, including total amount owing. Selection c...",""],
["./rep6.html","Debtors list","﻿Debtors list Top Previous Next This report contains the information on all business partners - debtors, including total amount owed. Selection cr...",""],
["./rep7.html","Goods balances log","﻿Goods balances log Top Previous Next This report contains the information on all goods currently available at warehouse (all company warehouses)....",""],
["./rep8.html","Business partner report","﻿Business partner report Top Previous Next Business partner report contains the information an all transactions (incoming and outgoing) on a selec...",""],
["./rep9.html","Goods movement report","﻿Goods movement report Top Previous Next This report is intended for preview and printing of the data on goods received and issued indicating docu...",""],
["./reports.html","Reports","﻿Reports Top Previous Next This important category helps you to obtain an overall review of data stored in the database. You can see common or det...",""],
["./server.html","OK-Server explained","﻿The OK-Server application should be automatically launched by request from the clients application. To accomplish that task there exists another ...",""],
["./systemrequirements.html","System Requirements","﻿Minimal requirements: Operating system: Microsoft Windows 2000 SP4, XP SP2 or Vista SP1. CPU: Single 500 Mhz for Windows 2000 and XP* RAM: 256 Mb...",""],
["./tfmaccounttype.html","Account types","﻿Account types Top Previous Next Error ",""],
["./tfmaccout.html","Invoices","﻿Invoices Top Previous Next Main table (document list) • icon - invoice type of document icon. • icon - for Completed (fully paid and shipped good...",""],
["./tfmbank.html","Banks","﻿Banks Top Previous Next Error ",""],
["./tfmchargetype.html","Expense categories","﻿Expense categories Top Previous Next Error ",""],
["./tfmcountries.html","Countries","﻿Countries Top Previous Next Error ",""],
["./tfmcurrency.html","Currencies","﻿The main table at the top show the list of available currencies with their names and last set exchange rate to the base currency . To add new cur...",""],
["./tfmkagent.html","Business partners","﻿Business partners Top Previous Next In fact this is the compound list of all your suppliers, clients and your own companies. icon indicates that ...",""],
["./tfmmaterials.html","Products","﻿Products directory Top Previous Next The main grid is simple and self-defining. there is Name and model of the product displayed along with measu...",""],
["./tfmmeasures.html","Measurements","﻿Measurements Top Previous Next Error ",""],
["./tfmoperlog.html","Event log","﻿Event Log Top Previous Next Clicking on «Event Log» will bring up an informational screen containing the data on all operations that took place i...",""],
["./tfmpricetypes.html","Price categories","﻿Price categories Top Previous Next Error ",""],
["./tfmusers.html","Users","﻿Users Top Previous Next Here you can add and edit the permissions for the users of this database. This is the current database users list. Each d...",""],
["./tfmwaybill.html","Goods Receipt Slips","﻿Goods Receipt Slips Top Previous Next Quick filter bar At the top of the window there is a bar with a few sorting options available to you. You m...",""],
["./tfmwaybillout.html","Editing","﻿Editing Goods Dispatch Slip Top Previous Next Main properties There are two important controls at the top left corner of the editing window: Post...",""],
["./tfmwbrest.html","Goods Balances Entry","﻿Goods Balances Entry Top Previous Next This document is necessary when you are just starting work with OK-Inventory, creating a new database or a...",""],
["./tfmwhouse.html","Warehouses and stores","﻿Warehouses/Stores Top Previous Next error ",""],
["./tfrmcoloptions.html","Set up columns","﻿This dialog is simple as it is. You click in the \"Display\" filed to enable or disable the display of chosen column. You also may rearrange column...",""],
["./tfrmcurrencyedit.html","Editing","﻿Editing the currency settings Top Previous Next Basically you enter the full and short names of the currency, keeping in mind that short name wil...",""],
["./tfrmeditaccout.html","Editing","﻿Editing invoice Top Previous Next Main properties • No. - Document ID number. Default is sequence number with user defined prefix and suffix from...",""],
["./tfrmeditkagent.html","Editing","﻿Editing details on business partner Top Previous Next When you adding a new record you have to choose the type first. It can be \"Companies\" for b...",""],
["./tfrmeditmaterials.html","Adding or Editing","﻿Adding or editing product Top Previous Next The topmost part of the general section is the main product details. Here you see that you editing th...",""],
["./tfrmeditposition.html","Adding/Editing Product Items","﻿Adding/Editing Product Items Top Previous Next This is the main product selection tools. Search Options allows you to define product search crite...",""],
["./tfrmeditpositionacc.html","Adding/Editing Product Items","﻿Adding/Editing Product Items Top Previous Next This is the main product selection tool. First you need to decide if you wish to reserve certain q...",""],
["./tfrmeditpositionsvc.html","Adding/Editing Service Items","﻿Adding/Editing Service Items Top Previous Next Adding a service is less complicated that adding a product. Select a service from the list of user...",""],
["./tfrmeditwaybill.html","Editing","﻿Editing Goods Receipt Slips Top Previous Next Main properties Main properties of the document being edited are displayed at the top left corner o...",""],
["./tfrmeditwaybillmov.html","Editing","﻿Editing goods transfer slip Top Previous Next Main properties Here you define document ID number, source and destination warehouses. • Employee -...",""],
["./tfrmeditwbrest.html","Editing","﻿Goods Balances Entry Editing Top Previous Next Main properties It is simple and straightforward. Check if document is Posted, enter the date and ...",""],
["./tfrmmatmove.html","Product movement information","﻿Error ",""],
["./tfrmmatrsv.html","Product reserve information","﻿Error ",""],
["./tfrmusersedit.html","Adding and Editing","﻿Adding and Editing user info Top Previous Next In the main section you define the login or username of the user which he or she will use at the l...",""],
["./tfrmwaybillout.html","Goods Dispatch Slips","﻿Goods Dispatch Slips Top Previous Next Quick filter bar At the top of the window there is a bar with a few sorting options available to you. You ...",""],
["./tools.html","Tools","﻿Tools Top Previous Next &#39;Settings&#39;: - it is main options for the OK-Inventory Users - these settings will define the names and access rights for ...",""],
["./unposting_rules.html","Unposting rules","﻿Unposting rules Top Previous Next If you want to unpost the document, you should keep in mind the following: Unposting is only possible if the pr...",""]];
